package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestUpgradeFromLegacyLayout emulates a workspace generated by an older
// speckeep (pre-skills-first per-command wrappers, nested `sdd/phases/`, and
// the OpenCode slash-command set) and verifies the documented upgrade path:
// doctor flags every stale artifact, refresh removes them and lays down the
// new skill pack, OpenCode ends up skills-only, user data survives, and doctor
// is clean afterwards.
func TestUpgradeFromLegacyLayout(t *testing.T) {
	root := t.TempDir()

	if _, stderr, err := executeRoot(t, "init", root, "--git=false", "--lang", "en", "--shell", "sh", "--agents", "claude,opencode"); err != nil {
		t.Fatalf("init returned error: %v (%s)", err, stderr)
	}

	legacyFiles := []string{
		".claude/commands/speckeep.spec.md",
		".claude/commands/spk.spec.md",
		".opencode/commands/spk-spec.md",
		".opencode/commands/spk-plan.md",
		".claude/skills/sdd/phases/spec.md",
	}
	for _, relPath := range legacyFiles {
		full := filepath.Join(root, filepath.FromSlash(relPath))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatalf("MkdirAll(%s): %v", full, err)
		}
		if err := os.WriteFile(full, []byte("legacy artifact\n"), 0o644); err != nil {
			t.Fatalf("WriteFile(%s): %v", full, err)
		}
	}

	userFeature := filepath.Join(root, "docs", "user-note.md")
	if err := os.MkdirAll(filepath.Dir(userFeature), 0o755); err != nil {
		t.Fatalf("MkdirAll(%s): %v", userFeature, err)
	}
	if err := os.WriteFile(userFeature, []byte("# user feature\n"), 0o644); err != nil {
		t.Fatalf("WriteFile(%s): %v", userFeature, err)
	}

	stdout, stderr, _ := executeRoot(t, "doctor", root)
	doctorOutput := stdout + stderr
	for _, relPath := range legacyFiles {
		if !strings.Contains(doctorOutput, filepath.FromSlash(relPath)) {
			t.Fatalf("doctor did not flag legacy artifact %s\n%s", relPath, doctorOutput)
		}
	}

	if _, stderr, err := executeRoot(t, "refresh", root); err != nil {
		t.Fatalf("refresh returned error: %v (%s)", err, stderr)
	}

	for _, relPath := range legacyFiles {
		if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(relPath))); !os.IsNotExist(err) {
			t.Fatalf("%s should have been removed by refresh (err=%v)", relPath, err)
		}
	}

	for _, relPath := range []string{
		".claude/skills/spk-spec/SKILL.md",
		".claude/skills/spk-plan/SKILL.md",
		".opencode/skills/spk-spec/SKILL.md",
	} {
		if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(relPath))); err != nil {
			t.Fatalf("expected new artifact %s after refresh: %v", relPath, err)
		}
	}

	if _, err := os.Stat(filepath.Join(root, ".opencode", "commands")); !os.IsNotExist(err) {
		t.Fatalf("opencode must be skills-only: .opencode/commands still present (err=%v)", err)
	}

	if content, err := os.ReadFile(userFeature); err != nil || string(content) != "# user feature\n" {
		t.Fatalf("user feature data was lost or changed: content=%q err=%v", content, err)
	}

	afterStdout, afterStderr, _ := executeRoot(t, "doctor", root)
	doctorOutput = afterStdout + afterStderr
	if strings.Contains(doctorOutput, "missing .opencode/commands") {
		t.Fatalf("doctor still expects opencode slash commands\n%s", doctorOutput)
	}
	if strings.Contains(doctorOutput, "legacy") {
		t.Fatalf("doctor still reports legacy artifacts after refresh\n%s", doctorOutput)
	}
}
